print("How old are you?", end=' ')
age = input()
print("How tall are you in metres?", end=' ')
height = input()
print("How much do you weigh in kg?", end=' ')
weight = input()
print("This is test?", end=' ')
test = input()

print(f"{test} So, you're {age} old, {height} tall and {weight} heavy.")