# Generated by Django 3.2.4 on 2021-07-15 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default.jpeg', upload_to='profile_pics')),
                ('full_name', models.CharField(default='pls update', max_length=250)),
                ('nric', models.CharField(default='pls update', max_length=15)),
                ('phone_no', models.CharField(default='pls update', max_length=25)),
                ('state', models.CharField(default='pls update', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
