# Generated by Django 3.2.4 on 2021-07-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthinfo',
            old_name='chills',
            new_name='question1',
        ),
        migrations.RenameField(
            model_name='healthinfo',
            old_name='diarrhea',
            new_name='question2',
        ),
        migrations.RenameField(
            model_name='healthinfo',
            old_name='fever',
            new_name='question3',
        ),
        migrations.RenameField(
            model_name='healthinfo',
            old_name='headache',
            new_name='question4',
        ),
        migrations.RenameField(
            model_name='healthinfo',
            old_name='vomiting',
            new_name='question5',
        ),
        migrations.AddField(
            model_name='healthinfo',
            name='question6',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
    ]
